[Service]
User=civiclenz-hermes
Group=civiclenz-hermes
LoadCredential=database-password:/etc/civiclenz/hermes-database.password
ExecStart=
ExecStart=/usr/bin/python3 /opt/civiclenz/hermes-bootstrap/8e7b3cd10d90449a5afffbd54bdff7796a17b217/database_bootstrap.py
