import Link from 'next/link';
import { DemoAvatar } from '@/components/demo-avatar';
import { Icon } from '@/components/icons';
import { MapVisual } from '@/components/map-visual';
import { activityItems, demoOfficials } from '@/lib/demo-data';

const sidebarItems = [
  ['Dashboard', '/dashboard/', 'home'], ['My Officials', '/watchlist/', 'users'], ['Alerts', '/alerts/', 'bell'], ['AI Monitor', '/monitor/', 'watch'], ['Promise Tracker', '/monitor/', 'target'], ['Contact Officials', '/sign-up/', 'message'], ['Petitions', '/petitions/', 'edit'], ['My Activity', '/monitor/', 'chart'], ['Reports', '/monitor/', 'file'], ['Settings', '/sign-up/', 'settings'],
] as const;

export function AppShell({ active, children }: { active: string; children: React.ReactNode }) {
  return <div className="app-shell"><aside className="app-sidebar"><Link href="/" className="app-sidebar-logo"><img src="/brand/civicslenz-mark.svg" alt="" /><span>Civics<b>LenZ</b></span></Link><nav>{sidebarItems.map(([label, href, icon]) => <Link href={href} key={label} className={label === active ? 'active' : ''}><Icon name={icon} size={18} /><span>{label}</span></Link>)}</nav><Link className="app-logout" href="/"><Icon name="logout" size={18} /> Log Out</Link></aside><section className="app-content"><header className="app-topbar"><div className="mobile-app-name"><img src="/brand/civicslenz-mark.svg" alt="" /> CivicsLenZ</div><div className="app-topbar-actions"><button type="button" aria-label="Search"><Icon name="search" size={20} /></button><button type="button" aria-label="Alerts"><Icon name="bell" size={20} /></button><span className="app-user-dot">AS</span></div></header>{children}</section></div>;
}

const metrics = [['12', 'Officials', 'Following'], ['5', 'Alerts', 'New'], ['3', 'Promises', 'Broken'], ['2', 'Petitions', 'You Signed']];

export function DashboardView() {
  return <AppShell active="Dashboard"><div className="app-page"><section className="app-greeting"><div><span className="small-label">YOUR CIVICLENZ</span><h1>Good morning, Alex <span>👋</span></h1><p>Here&apos;s what&apos;s happening with your officials.</p></div><Link className="btn btn-primary btn-small" href="/search/">Find officials <Icon name="arrow-right" size={15} /></Link></section><section className="dashboard-metrics">{metrics.map(([number, label, detail]) => <article key={label}><b>{number}</b><span>{label}</span><small>{detail}</small></article>)}</section><section className="dashboard-grid"><article className="app-card monitor-overview"><div className="app-card-heading"><div><span className="small-label">AI MONITORING OVERVIEW</span><h2>What we&apos;re watching for you</h2></div><Link href="/monitor/">View all <Icon name="arrow-right" size={15} /></Link></div><p className="muted-copy">We&apos;re watching 12 officials across 4 levels of government.</p><div className="monitor-table"><div><span className="monitor-dot blue" /><b>Tracked Promises</b><strong>1,248</strong><em>+10%</em></div><div><span className="monitor-dot green" /><b>Votes Tracked</b><strong>37</strong><em>+8%</em></div><div><span className="monitor-dot orange" /><b>Campaign Promises</b><strong>24</strong><em>Tracking</em></div><div><span className="monitor-dot red" /><b>Presidential Actions</b><strong>3</strong><em>New</em></div></div></article><RecentAlerts /></section><section className="dashboard-bottom"><article className="app-card user-map"><div className="app-card-heading"><div><span className="small-label">YOUR OFFICIALS ON THE MAP</span><h2>Representation at a glance</h2></div><Icon name="map" size={20} /></div><MapVisual compact /></article><QuickActions /></section></div></AppShell>;
}

function RecentAlerts() { return <article className="app-card recent-alerts"><div className="app-card-heading"><div><span className="small-label">RECENT ALERTS</span><h2>New since your last visit</h2></div><Link href="/alerts/">View all</Link></div>{activityItems.slice(0, 3).map((item) => <div className="recent-alert" key={item.title}><span className={`activity-icon ${item.tone}`}><Icon name="bell" size={13} /></span><div><b>{item.title}</b><small>{item.date}</small></div><Icon name="chevron-right" size={16} /></div>)}</article>; }

function QuickActions() { return <article className="quick-action-card dashboard-action-card"><span className="small-label">TAKE ACTION</span><h2>Your voice matters.</h2><Link href="/sign-up/" className="quick-action blue"><Icon name="message" size={21} /><span><b>Contact an Official</b><small>Send a message with AI assistance</small></span></Link><Link href="/petitions/" className="quick-action red"><Icon name="edit" size={21} /><span><b>Start a Petition</b><small>Create or support a public petition</small></span></Link></article>; }

export function MonitorView({ section = 'AI Monitor' }: { section?: 'AI Monitor' | 'Alerts' | 'My Officials' }) {
  const title = section === 'Alerts' ? 'Alerts that matter to you' : section === 'My Officials' ? 'Your civic watchlist' : 'AI monitoring center';
  return <AppShell active={section}><div className="app-page"><section className="app-greeting"><div><span className="small-label">{section.toUpperCase()}</span><h1>{title}</h1><p>{section === 'Alerts' ? 'Review notable changes and decide what deserves your attention.' : section === 'My Officials' ? 'The people and offices you chose to follow.' : 'A clear queue of source-backed changes, records, and action opportunities.'}</p></div><button className="btn btn-outline btn-small" type="button"><Icon name="settings" size={16} /> Preferences</button></section>{section === 'My Officials' ? <WatchlistContent /> : <MonitoringContent alertOnly={section === 'Alerts'} />}</div></AppShell>;
}

function MonitoringContent({ alertOnly }: { alertOnly: boolean }) { const records = alertOnly ? [...activityItems, ...activityItems.slice(0, 2)] : activityItems; return <section className="monitoring-layout"><article className="app-card monitoring-feed"><div className="feed-filter-row"><button className="filter-pill active" type="button">All activity</button><button className="filter-pill" type="button">Promises</button><button className="filter-pill" type="button">Votes</button><button className="filter-pill" type="button">News</button></div>{records.map((item, index) => <article className="monitoring-item" key={`${item.title}-${index}`}><span className={`activity-icon ${item.tone}`}><Icon name={item.type === 'Vote' ? 'check' : item.type === 'Promise' ? 'target' : item.type === 'Bill' ? 'file' : 'message'} size={17} /></span><div><span className="small-label">{item.type} · {item.date}</span><h2>{item.title}</h2><p>Illustrative monitoring summary. The production version will show source links, context, the official involved, and an audit trail.</p><div className="monitoring-actions"><button type="button">View source</button><button type="button">Follow update</button></div></div><Icon name="chevron-right" size={20} /></article>)}</article><aside className="app-card monitoring-side"><span className="small-label">YOUR SETTINGS</span><h2>Keep the signal useful.</h2><div className="side-setting"><Icon name="bell" size={19} /><span><b>Alert frequency</b><small>Daily digest</small></span><Icon name="chevron-right" size={16} /></div><div className="side-setting"><Icon name="target" size={19} /><span><b>Issues followed</b><small>Housing, schools, public money</small></span><Icon name="chevron-right" size={16} /></div><div className="side-setting"><Icon name="users" size={19} /><span><b>Officials watched</b><small>12 active profiles</small></span><Icon name="chevron-right" size={16} /></div></aside></section>; }

function WatchlistContent() { return <section className="watchlist-grid">{demoOfficials.slice(0, 5).map((official) => <Link href={`/officials/${official.slug}/`} className="watchlist-card" key={official.slug}><DemoAvatar official={official} size="lg" /><div><span className="small-label">{official.level}</span><h2>{official.name}</h2><p>{official.title}</p><span className="watch-score"><Icon name="sparkles" size={15} /> {official.score}/100 accountability score</span></div><Icon name="chevron-right" size={20} /></Link>)}</section>; }
