'use client';

import Link from 'next/link';
import { useState } from 'react';
import { DemoAvatar } from '@/components/demo-avatar';
import { Icon } from '@/components/icons';
import { demoOfficials, demoPetitions } from '@/lib/demo-data';

export function PetitionsExperience() {
  const [active, setActive] = useState('Active Petitions');
  const [signed, setSigned] = useState<string[]>([]);
  return <section className="petitions-page"><div className="site-width"><div className="prototype-label"><Icon name="sparkles" size={15} /> Petition pages are fully laid out for the UI prototype. Signatures and organizations below are sample data until the secure production workflow is connected.</div><div className="petitions-shell"><header className="petitions-header"><div><span className="small-label">CIVIC ACTION CENTER</span><h1>Petitions</h1><p>Discover and support petitions to hold officials accountable.</p></div><Link className="btn btn-primary btn-small" href="/sign-up/"><Icon name="plus" size={16} /> Start a petition</Link></header><div className="petition-tabs">{['Active Petitions', 'Petitions You Signed'].map((item) => <button type="button" onClick={() => setActive(item)} className={active === item ? 'active' : ''} key={item}>{item}</button>)}</div><div className="petition-list">{demoPetitions.map((petition, index) => { const official = demoOfficials[index % demoOfficials.length]; const isSigned = signed.includes(petition.slug); const signatures = petition.signatures + (isSigned ? 1 : 0); const progress = Math.round(signatures / petition.goal * 100); return <article className="petition-row" key={petition.slug}><DemoAvatar official={official} size="lg" /><div className="petition-copy"><span className="petition-category" style={{ '--petition-color': petition.color } as React.CSSProperties}>{petition.category}</span><h2>{petition.title}</h2><p>Started by <b>{petition.official}</b> · {petition.age}</p><div className="petition-progress"><span><i style={{ width: `${Math.min(progress, 100)}%`, background: petition.color }} /></span><b>{signatures.toLocaleString()} / {petition.goal.toLocaleString()} signatures</b><small>{progress}% of goal</small></div></div><div className="petition-actions"><Link href={`/petitions/${petition.slug}/`} className="btn btn-outline btn-small">View</Link><button type="button" className={`btn btn-small ${isSigned ? 'btn-signed' : 'btn-danger'}`} onClick={() => setSigned((values) => isSigned ? values.filter((slug) => slug !== petition.slug) : [...values, petition.slug])}>{isSigned ? <><Icon name="check" size={15} /> Signed</> : 'Sign Petition'}</button></div></article>; })}</div></div></div></section>;
}

export function PetitionDetail({ slug }: { slug: string }) {
  const petition = demoPetitions.find((item) => item.slug === slug) ?? demoPetitions[0];
  const [signed, setSigned] = useState(false);
  const signatures = petition.signatures + (signed ? 1 : 0);
  const progress = Math.round(signatures / petition.goal * 100);
  return <section className="petition-detail"><div className="site-width"><Link className="back-link petition-back" href="/petitions/"><Icon name="arrow-left" size={16} /> Back to petitions</Link><div className="petition-detail-grid"><article className="petition-article"><span className="petition-category" style={{ '--petition-color': petition.color } as React.CSSProperties}>{petition.category}</span><h1>{petition.title}</h1><p className="petition-lede">{petition.summary}</p><div className="petition-hero-meta"><span><Icon name="users" size={17} /> Started by CivicLenZ community member</span><span><Icon name="calendar" size={17} /> {petition.age}</span></div><div className="petition-story"><h2>Why this petition matters</h2><p>This page shows the exact place where a petition&apos;s background, requested action, verified source materials, and updates will appear. It gives supporters enough context to make an informed decision before adding their name.</p><p>In production, every petition will have a clear author, moderation status, official target, signatures, update history, and anti-fraud controls. No signature is collected by this visual prototype.</p><h2>Requested action</h2><ul><li>Publish the relevant public plan in plain language.</li><li>Set a specific timeline for action and public updates.</li><li>Provide a visible response from the relevant office.</li></ul></div></article><aside className="petition-sign-card"><span className="small-label">ADD YOUR VOICE</span><h2>{signatures.toLocaleString()} people have signed.</h2><div className="petition-detail-progress"><span><i style={{ width: `${Math.min(progress, 100)}%`, background: petition.color }} /></span><div><b>{progress}%</b><small>of {petition.goal.toLocaleString()} signature goal</small></div></div><button type="button" className={`btn btn-large ${signed ? 'btn-signed' : 'btn-danger'}`} onClick={() => setSigned(!signed)}>{signed ? <><Icon name="check" size={17} /> Petition Signed</> : <><Icon name="edit" size={17} /> Sign this Petition</>}</button><p>{signed ? 'Your prototype signature was added locally. In production, this step will use verified account confirmation.' : 'Prototype only — no real signature is submitted from this branch.'}</p><div className="petition-share"><span>Share the issue</span><button type="button"><Icon name="share" size={18} /> Share</button></div></aside></div></div></section>;
}
