"""Compile inactive versioned contracts into the existing canonical schema.

No database connection or activation. The supervisor reviews/applies emitted SQL
with the established operator channel. v1 records and Seat bindings are untouched.
Full scope semantics live in source_priority.contract_scope; policy is deliberately
empty so old source-key routers cannot interpret source roles as approved sources.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import uuid

CATALOG = Path(__file__).resolve().parents[2] / 'contracts/research/national-v2.json'
NAMESPACE = uuid.UUID('3a45a06f-7c9e-5c5b-aa5a-3489b9e223de')


def load_catalog(path=CATALOG):
    catalog = json.loads(Path(path).read_text())
    if catalog['formatVersion'] != 1 or catalog['activation'] != 'INACTIVE_UNBOUND':
        raise ValueError('Unsupported catalog format/activation')
    for key, contract in catalog['officeClasses'].items():
        if (not re.fullmatch(r'[A-Z_]+', key) or contract['officeClass'] != key
                or contract['contractKey'] != key + '_V' + contract['version']
                or contract['active'] is not False or not contract['scopes']
                or len(set(contract['scopes'])) != len(contract['scopes'])):
            raise ValueError('Invalid or active contract')
        for scope_key in contract['scopes']:
            scope = catalog['scopeDefinitions'][scope_key]
            if (scope['scopeKey'] != scope_key or not scope['sourcePriority']
                    or scope['activation'] != 'CAPABILITY_NOT_IMPLEMENTED'
                    or scope['publicationPolicy']['state'] != 'SEPARATE_GATE'
                    or scope['verification']['candidateRecordsAreProof'] is not False
                    or scope['freshnessDays'] <= 0 or scope['monitoringDays'] <= 0
                    or not scope['applicability'] or not scope['temporalPolicy']):
                raise ValueError('Incomplete scope policy')
            if scope['kind'] == 'dataset' and (
                    scope['datasetReconciliation'].get('samplingAllowed') is not False
                    or not scope['datasetReconciliation'].get('requirements')):
                raise ValueError('Finite dataset needs exhaustive reconciliation')
    return catalog


def rows(catalog):
    contracts, fields = [], []
    for spec in catalog['officeClasses'].values():
        contract_id = str(uuid.uuid5(NAMESPACE, spec['contractKey']))
        contracts.append({'research_contract_id': contract_id,
            **{column: spec[key] for column, key in (
                ('contract_key','contractKey'),('name','name'),('office_class','officeClass'),
                ('version','version'),('active','active'),('description','description'))}})
        for order, key in enumerate(spec['scopes']):
            scope = catalog['scopeDefinitions'][key]
            fields.append({'research_contract_field_id': str(uuid.uuid5(NAMESPACE, spec['contractKey']+'/'+key)),
                'research_contract_id': contract_id, 'field_key': key, 'category': scope['category'],
                'required_for_baseline': scope['requiredForBaseline'],
                'verification_requirement': 'contract_scope_v1',
                'source_priority': {'policy': '', 'contract_scope': scope,
                                    'library_version': catalog['libraryVersion']},
                'volatility_class': scope['volatility'], 'recheck_policy': str(scope['monitoringDays'])+'d',
                'sensitivity_rule': 'publication_eligible_claims_only', 'sort_order': order})
    return contracts, fields


def render_sql(catalog):
    contracts, fields = rows(catalog)
    output = ['-- Generated by contract_library.py; inactive/unbound; no civic truth writes.',
              'BEGIN;', 'SET LOCAL standard_conforming_strings = on;', "SET LOCAL lock_timeout = '3s';", "SET LOCAL statement_timeout = '30s';",
              'SELECT pg_advisory_xact_lock(184913, 7);']
    for table, records, pk in [('research_contracts', contracts, 'research_contract_id'),
                               ('research_contract_fields', fields, 'research_contract_field_id')]:
        data = json.dumps(records, sort_keys=True, separators=(',', ':')).replace("'", "''")
        columns = ','.join(records[0])
        # Constant table/column names; data uses escaped SQL strings. Compare every
        # supplied attribute after insert, rejecting drift rather than overwriting it.
        output.append(f"""DO $install$
DECLARE expected jsonb; actual jsonb;
BEGIN
 FOR expected IN SELECT value FROM jsonb_array_elements('{data}'::jsonb) LOOP
  INSERT INTO public.{table} ({columns})
   SELECT {columns} FROM jsonb_populate_record(NULL::public.{table}, expected)
   ON CONFLICT DO NOTHING;
  SELECT to_jsonb(t) INTO actual FROM public.{table} t WHERE {pk}=(expected->>'{pk}')::uuid;
  IF actual IS NULL OR NOT actual @> expected THEN
   RAISE EXCEPTION 'Immutable contract installation mismatch in {table}';
  END IF;
 END LOOP;
END $install$;""")
    # Catalog-level implementation work is durable even before Seats are bound.
    # These are implementation incidents, never fictitious ResearchNeeds/results.
    gaps = [{'incident_key': 'contract-capability:v2:'+field['research_contract_field_id'],
             'incident_class': 'CAPABILITY_NOT_IMPLEMENTED',
             'affected_references': {key: field[key] for key in
                 ('research_contract_id', 'research_contract_field_id', 'field_key')},
             'observations': {'state': 'CAPABILITY_NOT_IMPLEMENTED',
                 'capability': field['source_priority']['contract_scope']['capability'],
                 'contract_activation': 'INACTIVE_UNBOUND', 'dispatch_allowed': False,
                 'required_action': 'implement_and_physically_prove_exact_contract_capability',
                 'factual_no_result': False}}
            for field in fields if field['source_priority']['contract_scope']['required']]
    data = json.dumps(gaps, sort_keys=True, separators=(',', ':')).replace("'", "''")
    output.append(f"""INSERT INTO hermes_ops.incidents
      (incident_key,incident_class,affected_references,observations)
      SELECT incident_key,incident_class,affected_references,observations
      FROM jsonb_populate_recordset(NULL::hermes_ops.incidents, '{data}'::jsonb)
      ON CONFLICT(incident_key) DO NOTHING;""")
    for contract in contracts:
        count = sum(f['research_contract_id'] == contract['research_contract_id'] for f in fields)
        output.append(f"""DO $count$ BEGIN
          IF (SELECT count(*) FROM public.research_contract_fields
              WHERE research_contract_id='{contract['research_contract_id']}'::uuid) <> {count} THEN
            RAISE EXCEPTION 'Unexpected fields in immutable contract version';
          END IF;
        END $count$;""")
    output.append('COMMIT;')
    return '\n'.join(output)+'\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--sql', type=Path, help='Write reviewable SQL; never execute it')
    args = parser.parse_args()
    catalog = load_catalog()
    contracts, fields = rows(catalog)
    sql = render_sql(catalog)
    if args.sql:
        args.sql.write_text(sql)
    print(json.dumps({'contracts': len(contracts), 'fields': len(fields), 'active': False,
        'sql_sha256': hashlib.sha256(sql.encode()).hexdigest(), 'executed': False}))
